modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "bulking"
version = "${version}"
displayName = "Bulking"
authors = "neirenoir"
description = '''
A plugin for Diet inspired by SOL: Valheim. Do away with hunger, just stuff your stomach for awesome buffs!
'''
logoFile = "${logoFile}"

[[dependencies.bulking]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bulking]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bulking]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bulking]]
modId = "diet"
mandatory = true
versionRange = "[2.1.1,)"
ordering = "AFTER"
side = "BOTH"
